### ISSUE TITLE
GH Archive BigQuery and Metabase investigation and research

### ISSUE THREAD

**Issue by Mini256** [ti-community-infra/ti-sync-bot#82]
### Is your feature request related to a Issue or PR (Optional)

None

### Describe the feature you'd like:

Investigate ways to use GH Archive BigQuery and Metabase together.

**Comment by hi-rustin** [comment]
I did some research.
1. it can be used in combination with metabase, but there is no way to use the public database directly, we need to create views for the public dataset to use. For more information, please see: https://github.com/metabase/metabase/issues/2273
2. bigquery query cost is too high, only one TB of free quota, after the quota is exceeded, each TB costs $5. Because we are using all the GitHub data, the query cost is too high.
3. A possible solution is that we only store our own organization's data, which should be enough for the free storage and query quota. (I am working on this)

**Comment by Mini256** [comment]
Plan to use DevStats instead. #94
